touch ups

diff --git a/affine/rootfs/etc/s6-overlay/s6-rc.d/init/run b/affine/rootfs/etc/s6-overlay/s6-rc.d/init/run
--- a/affine/rootfs/etc/s6-overlay/s6-rc.d/init/run
+++ b/affine/rootfs/etc/s6-overlay/s6-rc.d/init/run
@@ -3,9 +3,17 @@
 
 set -euo pipefail
 
+# Validate required configuration
+for key in DB_USERNAME DB_PASSWORD DB_HOSTNAME DB_PORT DB_DATABASE_NAME; do
+    if ! bashio::config.exists "$key"; then
+        bashio::log.fatal "Required configuration '$key' is missing!"
+        exit 1
+    fi
+done
+
 # Replace env
 AFFINE_INDEXER_ENABLED=false
-DATABASE_URL=postgresql://$(bashio::config 'DB_USERNAME'):$(bashio::config 'DB_PASSWORD')@$(bashio::config 'DB_HOSTNAME'):$(bashio::config 'DB_PORT')/$(bashio::config 'DB_DATABASE_NAME')
+DATABASE_URL="postgresql://$(bashio::config 'DB_USERNAME'):$(bashio::config 'DB_PASSWORD')@$(bashio::config 'DB_HOSTNAME'):$(bashio::config 'DB_PORT')/$(bashio::config 'DB_DATABASE_NAME')"
 REDIS_SERVER_HOST=127.0.0.1
 
 
